POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "user",
    "password": "test1234"
}
###

GET http://localhost:8080/users?id=ajdlaa11
Content-Type: application/json
Authorization: jwqdsezqoof
###

GET http://localhost:8080/users?name=Adisson
Content-Type: application/json
Authorization: td0yt5zi69
###

DELETE  http://localhost:8080/users?id=pxz3mxnscj
Content-Type: application/json
Authorization: td0yt5zi69
###

PUT http://localhost:8080/users
Content-Type: application/json
Authorization: qe37lvzftv7

{
    "age": 24,
    "email": "somemail@mail.com",
    "name": "Adisson",
    "workingPosition": 3
}