POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "user",
    "password": "test1234"
}
###

GET http://localhost:8080/users?id=ajdlaa11
Content-Type: application/json
Authorization: jwqdsezqoof